### ISSUE TITLE
关于steam新版皮肤

### ISSUE THREAD

**Issue by hibikiypa** [Jack-Myth/Threshold-Miku#1]
（抱歉以这种方式提出问题，我是一个GIThub新手）
9.17号V社更新steam的游戏库界面，原有皮肤安装上之后无法显示出透明的效果（库页面）
膜拜一下大佬，如果能回答一下我的话会非常开心

**Comment by Jack-Myth** [comment]
首先安装原版皮肤。
然后下载Steam新库界面的皮肤[https://github.com/Jack-Myth/Threshold-Miku/releases/tag/v1.0](https://github.com/Jack-Myth/Threshold-Miku/releases/tag/v1.0)
然后把库界面的皮肤放到Steam/steamui/skins/里，这个文件夹是不存在的，你可以新建一个
然后修改Steam/steamui/Index.html，在"\</html\>"之前添加
***<link href="skins/Threshold Miku/main.css" rel="stylesheet"\>***
然后就可以看得到皮肤了。

由于Steam会在启动时验证文件，所以请使用-noverifyfiles启动参数，否则index.html将会被steam还原

**Comment by hibikiypa** [comment]
不起作用，我加了参数启动，也改了index.html的内容，但是库页面依旧无法透明显示背景

**Comment by DreamOfStars** [comment]
我也是同样的问题，加了参数以及修改了index.html，库仍然不透明。对了想问一下侧边栏的宽度要修改
\Customization\Collapsed Sidebar\resource\layout下的哪个文件的哪里呢，感觉过宽有点不好看。
非常感谢大佬的作品

**Comment by Jack-Myth** [comment]
请确定你们的路径是正确的，对照着那个路径再仔细看一遍

**Comment by hibikiypa** [comment]
成功了，把大佬回复里面的链接打开下载最新的，然后扔到Steam/steamui/skins/里解压就ok，前面步骤和路径都没有问题。。出问题只是因为用的之前6月份发布的那个版本皮肤。。

> 
> 
> 我也是同样的问题，加了参数以及修改了index.html，库仍然不透明。对了想问一下侧边栏的宽度要修改
> \Customization\Collapsed Sidebar\resource\layout下的哪个文件的哪里呢，感觉过宽有点不好看。
> 非常感谢大佬的作品

**Comment by YSRoland** [comment]
昨天改了还可以的，今天steam小更了一下失效了

**Comment by hibikiypa** [comment]
> 
> 
> 昨天改了还可以的，今天steam小更了一下失效了

是的，我的也失效了，库的游戏列表和搜索栏的透明效果还在，右侧的游戏信息透明失效

**Comment by Jack-Myth** [comment]
@hibikiypa 
@YSRoland 
已修复，请下载最新版

**Comment by hibikiypa** [comment]
> 
> 
> @hibikiypa
> @YSRoland
> 已修复，请下载最新版

大佬！求联系方式

**Comment by hibikiypa** [comment]
![图片](https://user-images.githubusercontent.com/13904828/65264190-aee2cd80-db40-11e9-9deb-783ca2732b5d.png)
还是不行的说。。。

**Comment by Jack-Myth** [comment]
> @hibikiypa
> @YSRoland
> 已修复，请下载最新版
> 
> 大佬！求联系方式

SteamID: JackMyth
