### ISSUE TITLE
不会用

### ISSUE THREAD

**Issue by kikilloy** [Jack-Myth/Threshold-Miku#104]
怎么跟卖家秀不太一样？不仅不是我想要的，还变丑了，另外我想用定制器里的这张图，但为什么点了应用变成这个了？
![图片](https://github.com/Jack-Myth/Threshold-Miku/assets/82642640/0f5c0154-333a-40e5-bb74-355d9890d8f4)
这是Threshold的设置，求大佬给我看看
![图片](https://github.com/Jack-Myth/Threshold-Miku/assets/82642640/173d1e32-9934-461f-a0cd-011f5b9a7bb1)

**Comment by MurasameAy** [comment]
你不看之前的Iss吗？前面都把问题写出来了

**Comment by kikilloy** [comment]
抱歉，我没认真看之前iss，我以为只有我自己不会用，所以我才发的
