### ISSUE TITLE
There are four black corners in the head

### ISSUE THREAD

**Issue by DeemoTlz** [Jack-Myth/Threshold-Miku#11]
![image](https://user-images.githubusercontent.com/27603769/74524674-7a8e0480-4f5a-11ea-84b1-71e8167b72d2.png)
Hi

**Comment by Jack-Myth** [comment]
Due to the limit of the Steam VGUI, The avatar won't be a real circle. It actually an overlay on the rectangular avatar. So the corners can't be transparent.

**Comment by Jack-Myth** [comment]
Due to the limit of the Steam VGUI, The avatar won't be a real circle. It actually an overlay on the rectangular avatar. So the corners can't be transparent.
