### ISSUE TITLE
透明问题

### ISSUE THREAD

**Issue by wuchuanpu** [Jack-Myth/Threshold-Miku#12]
大佬你好，
请问我为什么库-主页可以变成透明的
而打开具体游戏时下方不是透明的（依旧是STEAM的UI）

**Comment by Jack-Myth** [comment]
因为具体游戏的页面文字很多，如果背景透明文字就会难以辨认。最终权衡了一下就没让它透明

**Comment by MWSMXW** [comment]
> 因为具体游戏的页面文字很多，如果背景透明文字就会难以辨认。最终权衡了一下就没让它透明

大佬你好，请问我可以自己修改吗，想改成透明的应该怎么操作？

**Comment by Jack-Myth** [comment]
如果你会css的话，你可以自己修改steamui/skins/Threshold Miku/main.css这个文件
