### ISSUE TITLE
Advice on Transparence upgrade

### ISSUE THREAD

**Issue by b4imetu** [Jack-Myth/Threshold-Miku#13]
Jack大佬你好，希望在下一版本中可以将`Dark`版本的默认设置背景全透明（就像你Markdown文件里展示的那样）。
- 只是UI四周有背景图片的话视觉效果其实不好。
如图[<img src="https://i.loli.net/2020/03/08/OMc4g5RYxHvmftA.png" >](url)
- 如果是暗色背景也不容易有“背景透明文字就会难以辨认”的问题
- `Dark`和`Light`的不同，也方便用户在两个版本中相互替换文件而不需要手动修改CSS的麻烦。
拜托了，期待回复。

**Comment by Jack-Myth** [comment]
你需要执行皮肤内的Install.cmd来安装新库界面的皮肤。安装完之后就会和Readme展示的一样了。
另外，执行完之后记得使用桌面上的快捷方式来启动Steam，否则皮肤会被Steam还原。
