### ISSUE TITLE
给大佬反应下建议嗷

### ISSUE THREAD

**Issue by Charles-LIU-TURBOBOOST** [Jack-Myth/Threshold-Miku#14]
大佬制作的miku壁纸应用在steam是没有问题，但是在商店页面的时候，miku的商店壁纸和主页壁纸不吻合。如果使用那个自制壁纸软件会打不开商店页面，还有好友页面级社区。如果换为原来的miku壁纸就可以正常使用。但求可自定义编辑的商店webpage。秋梨膏

**Comment by Jack-Myth** [comment]
商店页壁纸不吻合是因为地址栏的原因，皮肤默认是打开地址栏的，如果错位请把地址栏打开，或者在定制器里选择“New Webpage without URL”。
至于打不开商店页面，在我这里试了六张图片，网页都是正常的，并没能重现这个问题，请尝试用管理员权限打开，不清楚这样是否会好些。

**Comment by Charles-LIU-TURBOBOOST** [comment]
感谢大大的回复，现在问题已经解决，如果我后面遇到bug的话，我会及时在GitHub上向大大反馈的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JackMyth"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月28日(星期六) 上午9:53
收件人:&nbsp;"Jack-Myth/Threshold-Miku"<Threshold-Miku@noreply.github.com&gt;;
抄送:&nbsp;"2510832992"<2510832992@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Jack-Myth/Threshold-Miku] 给大佬反应下建议嗷 (#14)





 
商店页壁纸不吻合是因为地址栏的原因，皮肤默认是打开地址栏的，如果错位请把地址栏打开，或者在定制器里选择“New Webpage without URL”。
 至于打不开商店页面，在我这里试了六张图片，网页都是正常的，并没能重现这个问题，请尝试用管理员权限打开，不清楚这样是否会好些。
