### ISSUE TITLE
求大大告诉我商店、社区和账户的背景怎么更改（一直找不到它们背景图片的位置）

### ISSUE THREAD

**Issue by xilinSAMA** [Jack-Myth/Threshold-Miku#15]
![TIM图片20200329093633](https://user-images.githubusercontent.com/62795387/77837870-cc07f100-71a0-11ea-982d-6b840ab7fb0b.png)
求大大告诉这个页面背景的图片位置，秋梨膏o(*////▽////*)q

**Comment by xilinSAMA** [comment]
![TIM图片20200329094817](https://user-images.githubusercontent.com/62795387/77838036-7af8fc80-71a2-11ea-8785-165b325343c6.png)
如果可以的话，这根线的代码在哪里，我想把颜色和阴影改了（不得不说，虽然有几张图不知道用在哪里的，不过挺色的，我喜欢o(≧口≦)o）

**Comment by xilinSAMA** [comment]
![TIM截图20200329100037](https://user-images.githubusercontent.com/62795387/77838203-42f2b900-71a4-11ea-9cc1-b5c955289f8a.jpg)
还有这个页面不能像Previews文件夹所展示的那样可以显示出背景图片，还有下面这个好友这个页面的皮肤无法显示
![20200329100300](https://user-images.githubusercontent.com/62795387/77838229-877e5480-71a4-11ea-9c98-d55a66af5dae.png)

**Comment by Jack-Myth** [comment]
背景图片建议用定制器改(Threshold Miku Customizer 2.exe).
分割线在steamui\skins\Threshold Miku\main.css里，搜索library_LibraryWindowDivider
新库界面的游戏页现在没有背景图，新好友系统也没有背景图

**Comment by xilinSAMA** [comment]
这里还有个问题，无论操不操作，当我点应用的时候就会无响应，当然我看了一下，修改图片什么的操作是完成了，就是单纯的最后无响应
![TIM图片20200329193832](https://user-images.githubusercontent.com/62795387/77848105-ebc90480-71f4-11ea-874d-7c5b4de2b53b.png)

**Comment by xilinSAMA** [comment]
以及我发现音乐播放器皮肤替换后是残缺的（如图所示），然后我试着用你的可以显示的图和我的合成在一起，发现照片确实ke可以完全显示出来了，但是只能显示出原图初音轮廓内的图片（另一种残缺）
![TIM截图20200329194153](https://user-images.githubusercontent.com/62795387/77848640-c211dc80-71f8-11ea-9821-f036a85f65cb.jpg)

**Comment by xilinSAMA** [comment]
那个背景我刚刚用定制器试了，商店页面的背景还是初音的，没有变化
