### ISSUE TITLE
还有几个问题。。。。

### ISSUE THREAD

**Issue by xilinSAMA** [Jack-Myth/Threshold-Miku#16]
这里还有个问题，无论操不操作，当我点应用的时候就会无响应，当然我看了一下，修改图片什么的操作是完成了，就是单纯的最后无响应
![TIM图片20200329193832](https://user-images.githubusercontent.com/62795387/77848105-ebc90480-71f4-11ea-874d-7c5b4de2b53b.png)

还有那个背景我刚刚用定制器试了，商店页面的背景还是初音的，没有变化，不知道为什么，求解

**Comment by xilinSAMA** [comment]
以及我发现音乐播放器皮肤替换后是残缺的（如图所示），然后我试着用你的可以显示的图和我的合成在一起，发现照片确实ke可以完全显示出来了，但是只能显示出原图初音轮廓内的图片（另一种残缺）
![TIM截图20200329194153](https://user-images.githubusercontent.com/62795387/77848640-c211dc80-71f8-11ea-9821-f036a85f65cb.jpg)

**Comment by xilinSAMA** [comment]
大佬先别关，我这会儿一直会反馈的QAQ

**Comment by Jack-Myth** [comment]
停止工作可能是因为你的修改破坏了皮肤的结构，重新下载皮肤再应用。
音乐播放器的图片被限制在了那个区域里，你需要找一个跟它差不多大的图片。

**Comment by xilinSAMA** [comment]
那商店背景那个初音没有办法换掉吗
库可以正常替换，商店和社区那里依旧是一开始的初音，改不掉。。。。我也很菜，找不到他们的替换文件位置

**Comment by xilinSAMA** [comment]
![TIM截图20200329203941](https://user-images.githubusercontent.com/62795387/77849377-c4c30080-71fd-11ea-8327-1ba853d5097d.jpg)
![TIM截图20200329204126](https://user-images.githubusercontent.com/62795387/77849379-c7255a80-71fd-11ea-9639-87b753ba4a21.jpg)
你看，对比一下大概就是这样子

**Comment by Jack-Myth** [comment]
定制器应当是可以修改这个部分的，你重新下载皮肤了吗？手动修改可能会让定制器出现问题的

**Comment by xilinSAMA** [comment]
重新下载了，但是还是有问题

**Comment by Jack-Myth** [comment]
重新下载之后定制器还是会出现未响应的问题吗？

**Comment by xilinSAMA** [comment]
唯一我改的一点就是把那个原先的D:\steam\skins\Threshold Miku这个文件夹名换成了D:\steam\skins\BiliBili

**Comment by xilinSAMA** [comment]
是的

**Comment by xilinSAMA** [comment]
还有这个
D:\steam\skins\BiliBili\steamui\skins\Threshold Miku
D:\steam\steamui\skins\Threshold Miku
后面的Threshold Miku改掉了
当然里面main.css对应的名字我也改了

**Comment by Jack-Myth** [comment]
D:\steam\skins\BiliBili\steamui\skins\Threshold Miku这个不能改，如果改了会使定制器崩溃，后面的操作就没法进行了。
使用定制器就不要手动修改皮肤了，如果你要改名字，先用定制器处理完你的图片再改。

**Comment by xilinSAMA** [comment]
好的，谢谢了，我去看看能不能成功

**Comment by xilinSAMA** [comment]
可以了，名字啥的就不改了 ，那是心血来潮

**Comment by xilinSAMA** [comment]
D:\steam\skins\Threshold-Miku-Light
我发现商店那些页面替换不了的原因是这个文件夹名被改了（把名字改回去，然后再次用定制器修改MainBG才可以再次加载），看来真不能乱改名，谢谢大佬了
