### ISSUE TITLE
a little question

### ISSUE THREAD

**Issue by AToMbYE** [Jack-Myth/Threshold-Miku#17]
when i use my own wallpaper,i always can't open the store,and some of my wallpaper can make it,but the others can't.

**Comment by Jack-Myth** [comment]
Actually I can't reproduce this issue on my machine, so please give the bellow file to me, I will check it after some time.
1.The wallpaper you use.
2.Threshold Miku\resource\webkit.css
3.Threshold Miku\Customization\Backup\WebPageStyle\resource\webkit.css(rename it to a different name)

**Comment by AToMbYE** [comment]
那个啥，这个webkit.css是要我替换自己壁纸后的还是原本的

**Comment by Jack-Myth** [comment]
肯定是你替换过之后的呀

**Comment by AToMbYE** [comment]
![861989377568023208](https://user-images.githubusercontent.com/62850097/78015139-8ce1c780-737b-11ea-8b44-748bd3cbbf41.jpg)


那两个文件我传了你不知道看不看得到，我这边没显示，然后的话这张图原图是1600*1116的，放进去的时候是能加载出商店的，我PS改成1920*1080之后就加载不出来了。我怀疑是图片太大了，因为使用正常的original webpage是可以加载出来的。

**Comment by Jack-Myth** [comment]
只有一张图，没有CSS
