### ISSUE TITLE
A question about transparency

### ISSUE THREAD

**Issue by ghost** [Jack-Myth/Threshold-Miku#18]
I saw in the first image ：Threshold-Miku/Previews/ main.jpg, the selection of subgame is transparent, but I installed in the process, is not transparent, please tell me how to do?
https://github.com/Jack-Myth/Threshold-Miku/blob/Light/Previews/Main.jpg
My installation results:
https://s1.ax1x.com/2020/03/30/GeaMwT.png

**Comment by Jack-Myth** [comment]
They actually are two different UI.  The old library is transparent but the new library isn't. Because the new library has too many elements and animations, it's hard to make it transparent while keeping all the things easy to read.

**Comment by ghost** [comment]
I used the old version of steam UI file and it is ready to use. Thank you for your reply

**Comment by The-vicissitudes-of-life** [comment]
> 它们实际上是两个不同的UI。旧库是透明的，但新库不是。由于新库包含太多元素和动画，因此很难在保持所有内容易于阅读的同时使其透明。

I used the old version of steam UI file and it is ready to use. Thank you for your reply

**Comment by ghost** [comment]
> They actually are two different UI. The old library is transparent but the new library isn't. Because the new library has too many elements and animations, it's hard to make it transparent while keeping all the things easy to read.

I used the old version of steam UI file and it is ready to use. Thank you for your reply
