### ISSUE TITLE
你好，我想请问下，这三个选项有什么区别

### ISSUE THREAD

**Issue by yaodao0yaodao** [Jack-Myth/Threshold-Miku#19]
![image](https://user-images.githubusercontent.com/20895333/78529274-d9158780-7813-11ea-8525-dead84c3fe34.png)
我这样设置后
![image](https://user-images.githubusercontent.com/20895333/78529361-006c5480-7814-11ea-9ad7-c475af81bdd4.png)
的确库里面成全透明了
但是在商店界面依然是灰色半透明
请问下我是设置错了还是本来商店就改不了啊

**Comment by Jack-Myth** [comment]
商店界面不应该是灰色半透明的，你是否自己替换了图片？
如果是你自己替换了图片，可能是图片大小的原因，大于700KB的图片会使webkit.css失效，从而导致商店页没有背景图。
那三个选项是控制商店页面的，withURL是有地址栏，withoutURL是没有地址栏，Original是原始不带背景图的商店页
