### ISSUE TITLE
求更新dark主题的MainBG.jpg

### ISSUE THREAD

**Issue by Wildwizard404** [Jack-Myth/Threshold-Miku#2]
目前只有light主题的MainBG.jpg，dark主题改完之后虽然显示了图像但是非常滑稽，我觉得您能想象出来。我试着搜了一下没找到原图，只能请求更新了。
顺便[readme](https://github.com/Jack-Myth/Threshold-Miku#installation-1)中 3. Open Steam/steaui/index.html,  少了一个字母m

**Comment by Wildwizard404** [comment]
dev和F6可真实吓死人，差点社会性死亡……

**Comment by Jack-Myth** [comment]
![Hatsune Miku full 2106997](https://user-images.githubusercontent.com/25215643/65264323-ee111e80-db40-11e9-8a9f-58da1b6d3e27.jpg)

**Comment by Jack-Myth** [comment]
Dev和F6是给Developer的福利hhh
