### ISSUE TITLE
关于库里面分割线的修改

### ISSUE THREAD

**Issue by yaodao0yaodao** [Jack-Myth/Threshold-Miku#20]
分割线在steamui \ skins \ Threshold Miku \ main.css里，搜索library_LibraryWindowDivider

我根据上面这个地方修改发现只是修改了阴影的粗细和颜色。但是并没有删除黑线
![image](https://user-images.githubusercontent.com/20895333/78530659-aa4ce080-7816-11ea-8608-b99374253f40.png)
请问下完全删除分割线应该怎么做呢？

**Comment by Jack-Myth** [comment]
目前只能手动修改main.css，以后可能会考虑加入修改分割线的功能
