### ISSUE TITLE
Display of Library Background  [BUG]!

### ISSUE THREAD

**Issue by lw404-ai** [Jack-Myth/Threshold-Miku#21]
1、It doesn't display correctly in the game library background
![360截图20200406174802722](https://user-images.githubusercontent.com/61489913/78545874-16d3d980-782f-11ea-864e-c07028dd86b2.jpg)

2、The steam button and the back button coincide
![360截图20200406174838744](https://user-images.githubusercontent.com/61489913/78545978-44b91e00-782f-11ea-93c2-3362a1f6b1e0.jpg)

I look forward to your repairing this problem in time
Thank you for the tools

my email address : liwei-@outllok.com

:+1: :+1:

**Comment by Jack-Myth** [comment]
This button shouldn't be transparent, are you edit the files manually?

**Comment by lw404-ai** [comment]
No, I made it by using your tool

发自iPhone LW

在 2020年4月6日，下午6:29，JackMyth <notifications@github.com> 写道：

﻿

This button shouldn't be transparent, are you edit the files manually?

**Comment by Jack-Myth** [comment]
OK，I know this problem，I will try to fix it after some times

**Comment by lw404-ai** [comment]
Thanks


发自iPhone LW

在 2020年4月6日，下午6:36，JackMyth <notifications@github.com> 写道：

﻿

OK，I know this problem，I will try to fix it after some times

**Comment by lw404-ai** [comment]
I'd like to ask you how to modify the libraryroot.css file to make the images processed seamlessly
![360截图20200406185431167](https://user-images.githubusercontent.com/61489913/78551573-869a9200-7838-11ea-98b0-3ff4bac519f5.jpg)


Make it seamless like a store interface


![360截图20200406185456388](https://user-images.githubusercontent.com/61489913/78551691-ae89f580-7838-11ea-897c-970b4d869e1d.jpg)

**Comment by lw404-ai** [comment]
？？

**Comment by Jack-Myth** [comment]
Threshold-Miku should take effect on the Library, did you ever run the Install.cmd?

**Comment by lw404-ai** [comment]
thanks
I forget to run it

发自iPhone LW

在 2020年4月6日，下午7:36，JackMyth <notifications@github.com> 写道：

﻿

Threshold-Miku should take effect on the Library, did you ever run the Install.cmd?

**Comment by lw404-ai** [comment]
This page how can i make it to use picture?

![360截图20200406195106836](https://user-images.githubusercontent.com/61489913/78555750-4212f480-7840-11ea-8292-48106b41087a.jpg)

thanks

**Comment by Jack-Myth** [comment]
https://github.com/Jack-Myth/Threshold-Miku/issues/18#issuecomment-605953402
