### ISSUE TITLE
Threshold Miku Customizer 2工具使用问题

### ISSUE THREAD

**Issue by DeemoTlz** [Jack-Myth/Threshold-Miku#23]
1. 修改MainBG后一些功能无法使用
![image](https://user-images.githubusercontent.com/27603769/84152699-92ecd680-aa97-11ea-8b05-2e25547917a5.png)
商店页面加载失败，好友弹窗界面无法显示

2. Threshold Miku Customizer 2重置后，界面未完全恢复
![image](https://user-images.githubusercontent.com/27603769/84153088-068ee380-aa98-11ea-896b-91f17e99b788.png)
仍然存在的问题：商店页面加载失败，好友弹窗界面无法显示

**Comment by Jack-Myth** [comment]
重置的问题确实存在，但商店界面和好友界面的问题并非由皮肤导致。有玩家反馈图片越大商店加载就会越慢，你可以试试换张小图片

**Comment by DeemoTlz** [comment]
谢谢作者回复！
但是在1.5.0版本，我手动替换背景图片就不会出现这个问题（是同一张图片，在1.5.0版本我是自己生成的 `MainBG.tga`然后替换），请问在2.1.3版本怎么手动替换背景呢？
1.5.0版本手动替换背景分两步（`MainBG.tga` 和 `MainBG.jpg`），但是在2.1.3版本下，由于做了更新只找到 `..\graphics\JackMyth\MainBG.tga`，现在替换 `MainBG.tga` 只能修改显示一部分，请问要怎么手动替换背景呢？

**Comment by Jack-Myth** [comment]
需要同步替换webkit.css中的背景，背景以Base64编码，很长一串的那个就是。新版本不建议手动替换背景，建议使用定制器。新版本定制器已经修复了重置的问题。
