### ISSUE TITLE
Steam界面按钮图标不清晰

### ISSUE THREAD

**Issue by Leo204-LKY** [Jack-Myth/Threshold-Miku#24]
图：
![image](https://user-images.githubusercontent.com/57821066/85190348-28833400-b2ea-11ea-9774-78bcaa363552.png)

Steam左侧边栏按钮图标很糊
标题栏右边四个按钮也很糊
 
难道是屏幕分辨率的问题？3000×2000缩放200%

**Comment by Leo204-LKY** [comment]
不仅是主窗口，各种Threshold-Miku支持的窗口标题栏按钮也很糊……
![image](https://user-images.githubusercontent.com/57821066/85190476-66348c80-b2eb-11ea-9bbb-369662ff5c68.png)
![image](https://user-images.githubusercontent.com/57821066/85190494-97ad5800-b2eb-11ea-8bf7-39164c48f89d.png)
![image](https://user-images.githubusercontent.com/57821066/85190504-ad228200-b2eb-11ea-83eb-02a812fc4ab1.png)
（还有音乐播放器的播放暂停上一首下一首一类的按钮）
![image](https://user-images.githubusercontent.com/57821066/85190530-d216f500-b2eb-11ea-8578-b59196b66d21.png)
其他地方应该也一样emmm

**Comment by Leo204-LKY** [comment]
手一滑点到Close and comment了,,ԾㅂԾ,,

**Comment by Leo204-LKY** [comment]
另外能不能在三横线菜单增加TMC2的快捷启动呢？每次想做调整都要翻skins文件夹还是有些麻烦的

**Comment by Jack-Myth** [comment]
啊，这个问题确实存在，因为在我着手做ThresholdMiku的时候原版Threshold还没有开始进行高DPI适配，所以会出现这个问题。适配高DPI可能得等到我有时间再说了，先咕一阵。
然后那个快捷启动这个不打算加。因为TMC2本意是一个一次性的工具，加图片，调整调整，用完之后就不会再打开了。把这个工具加入到Steam本身的菜单里没有必要。如果你真的调整的这么频繁，可以在桌面上创建一个快捷方式。

**Comment by Leo204-LKY** [comment]
感谢回复
主要是想有时候想隐藏边栏有时候又不想隐藏，所以想要个快速启动

**Comment by Leo204-LKY** [comment]
UI这方面虽说不影响使用，但看得难受…

**Comment by Jack-Myth** [comment]
更新了新版本，增加了高DPI图标。

**Comment by Leo204-LKY** [comment]
太快了
我还以为一段时间要等很久呐
