### ISSUE TITLE
关于mainbg的分辨率

### ISSUE THREAD

**Issue by daoguang1012** [Jack-Myth/Threshold-Miku#25]
我试过很多分辨率的图片 甚至把他们改成您默认图片的一样的分辨率，但还是提示图片过大，商店界面打不开，网页那些都加载不了，除非选择不使用背景的页面

**Comment by Jack-Myth** [comment]
定制器对图片的分辨率没有限制。受限制的是图片的大小。图片大于700kB就会出问题。

**Comment by daoguang1012** [comment]
okk 谢谢！

**Comment by daoguang1012** [comment]
![image](https://user-images.githubusercontent.com/62734528/85819748-3aac1900-b7a7-11ea-98ee-fb0088290281.png)
![image](https://user-images.githubusercontent.com/62734528/85819757-4992cb80-b7a7-11ea-8611-f26f292ccef0.png)
还有一个问题 商店界面图片会错位 是我的问题还是bug呢？

**Comment by QingYunYo** [comment]
我也有错位的问题，一直都有，除了库以外的界面都会错位

**Comment by Jack-Myth** [comment]
在设置里勾选“在可用时显示SteamURL地址栏”，或者在定制器里选择有背景的网页（不带URL）“”

**Comment by daoguang1012** [comment]
okk 谢谢大佬 么么

**Comment by QingYunYo** [comment]
好了，谢谢
