### ISSUE TITLE
边栏按钮二级菜单的位置问题/建议

### ISSUE THREAD

**Issue by Leo204-LKY** [Jack-Myth/Threshold-Miku#26]
我又来了
![image](https://user-images.githubusercontent.com/57821066/85840721-8c689980-b7cf-11ea-9f00-a455346537f6.png)
关于左侧这个边栏，鼠标挪到相应的按钮上就会自动弹出二级菜单
![image](https://user-images.githubusercontent.com/57821066/85840798-aefab280-b7cf-11ea-8bef-80c2fa90b415.png)
但有时候其实是想按下面的按钮，而二级菜单会挡住下面的按钮
只能先将鼠标往左/右移关闭二级菜单后，再移动到其他按钮上
 
所以，二级菜单为什么不能放在按钮的右侧呢？
![image](https://user-images.githubusercontent.com/57821066/85841054-1d3f7500-b7d0-11ea-90f7-e55cae459cc8.png)
这样不就不会挡按钮了嘛

**Comment by Jack-Myth** [comment]
这个菜单的位置是由Steam硬编码的，只能位于下方，皮肤无法修改
