### ISSUE TITLE
MainBG的图片到底是怎样的要求

### ISSUE THREAD

**Issue by QingYunYo** [Jack-Myth/Threshold-Miku#29]
好多图都提示太大，背景可能不会生效，有提示的商店界面和社区界面就打开不了了。
4k的图提示比较大，然后商店和社区就用不了了，但我把图改成1920*1080的虽然也还是提示太大，但可以用，图片都没超过8MB。
所以对图片要求有疑问，望解答，谢谢

**Comment by Jack-Myth** [comment]
大小的限制不在于分辨率，而是图片文件的大小。Steam对于Webkit.css的解析有限制，当文件超过1MB后Steam会拒绝解析。图片需要转换成Base64编码才能够在Webkit.css中使用，而转换编码会使图片大小增加1/3，再加上css中其他内容，所以当图片大于700KB之后就会有问题。  
然后根据用户反馈，图片越大商店和社区打不开的概率也会越大，这个需要你自行尝试。

**Comment by xiao-e-yun** [comment]
我自己測試丟圖片內建修改器上（50%解析度左右的圖片 再壓縮色彩）後修改+保存關閉
然後再用轉碼器把原圖轉TGA，然後直接丟到圖片資料夾內的JackMyth上（修改成MainBG）
重啟steam       (1920*1080動漫圖）
