### ISSUE TITLE
Why can I only show some pictures?

### ISSUE THREAD

**Issue by alamanxp** [Jack-Myth/Threshold-Miku#3]
![1](https://user-images.githubusercontent.com/44918514/66294146-de545100-e91a-11e9-83b2-9c56e69525fb.png)

**Comment by alamanxp** [comment]
I hope he is.![Main](https://user-images.githubusercontent.com/44918514/66294309-3ee38e00-e91b-11e9-8ea1-fee849b92d3f.jpg)

**Comment by Jack-Myth** [comment]
You only applied the skin for SteamUI. You need both SteamUI and VGUI skin. Download the skin from the Releases page, extract the skin to Steam/skins, and goto Settings->Interface->Skins to enable it.
