### ISSUE TITLE
There are some issues with custom main background

### ISSUE THREAD

**Issue by YoroizukaMizore** [Jack-Myth/Threshold-Miku#30]
When I use the customizer 2 to set a new customized background, the steam library actually works, but when I click store or community, it end up showing nothing but black background. However, if I set "no background webpage", the steam library background did not show normally.

**Comment by Jack-Myth** [comment]
Based on some user reports, It's may because your picture file is too big, try a small one and it may be better.

**Comment by YoroizukaMizore** [comment]
Problem solved, thanks!
