### ISSUE TITLE
 steam web cannot be transparent

### ISSUE THREAD

**Issue by xiao-e-yun** [Jack-Myth/Threshold-Miku#32]
Is this problem can be solved?
![image](https://user-images.githubusercontent.com/67814228/86531261-4b206a00-bef2-11ea-868a-a27111af572c.png)

**Comment by Jack-Myth** [comment]
Your background picture is too big. Try a small one.

**Comment by xiao-e-yun** [comment]
Thank you
I'm done with him

JackMyth <notifications@github.com> 於 2020年7月6日 週一 01:24 寫道：

**Comment by xiao-e-yun** [comment]
You can send Compressed picture to the website
Use high-quality pictures locally
Blur the pictures on the website to create high quality
（Already tried）
或著你乾脆再簡介加個mainBG僅限上傳750KB的圖片
不然每次都會受到問題..
