### ISSUE TITLE
[Enhancement] Allow users to reset the background.

### ISSUE THREAD

**Issue by hv0905** [Jack-Myth/Threshold-Miku#34]
The background customize feature in the customize tool works nice for me. However, when I want to reset the background to theme's default, I have to reset the whole settings using the `Reset` button, which is confusing and inconvenient.
So I hope that there is a `reset current background` button, which only reset the background of the active panel.

**Comment by Jack-Myth** [comment]
Nice idea, It will be added in the next version

**Comment by Jack-Myth** [comment]
Updated
