### ISSUE TITLE
关于MainBG的一些问题

### ISSUE THREAD

**Issue by MoAccelerator** [Jack-Myth/Threshold-Miku#35]
在当前的版本中我可以使用与MainBG不同的图片来当做游戏列表的背景吗？
之前我一直使用的是1.2版本的Threshold-Miku 直到半年前才开始更换为新版本使用，当我上手新版本之后发现文件结构变了很多，经过一番摸索之后我发现更换背景时会改变webkit.css文件，便认为该文件是与背景有关的，但是由于我对css一窍不通 所以也看不出来什么端倪，如果有办法单独修改游戏列表背景的方法还请大大告知。。。
另外我使用一键更换器换皮肤的时候遇到了“图片过大 可能无法生效”的问题，我在Photoshop中1:1还原了默认皮肤的分辨率，并且压缩到比原皮肤文件还要小，却仍然提示我图片过大，强制更换之后打开steam会出现只有一圈背景 游戏库和主页等页面全部黑屏的情况，而且好友列表无法打开，我只能手动把PNG图片转码成TGA文件覆盖到graphics\JackMyth\   但是游戏列表的背景和主背景不统一，游戏列表的背景是原版背景，我估计问题就出在css文件里。。。手动更换MainBG换了相同的图片 除了游戏列表的背景有问题以外并无发现其他bug
希望可以解答一下，谢谢！
![image](https://user-images.githubusercontent.com/45995147/89359253-f2620e00-d6f7-11ea-99a6-48e9b2792d03.png)
                                                       ↑↑↑↑↑手动替换↑↑↑↑↑
![image](https://user-images.githubusercontent.com/45995147/89359315-16bdea80-d6f8-11ea-96ec-239854631fc0.png)
![image](https://user-images.githubusercontent.com/45995147/89359409-5a185900-d6f8-11ea-9e7e-7f6e91212fee.png)
                                                       ↑↑↑↑↑定制器替换↑↑↑↑↑

**Comment by Jack-Myth** [comment]
图片文件最大不能超过700kB，检查你的文件大小。
