### ISSUE TITLE
2.3.2

### ISSUE THREAD

**Issue by flyygph** [Jack-Myth/Threshold-Miku#37]
1.设置栏里面有几个地方点不了（表现为集中在左上角），例如下载限速
![image](https://user-images.githubusercontent.com/42086066/94369778-504d1980-00db-11eb-9e01-ca5341c0a82f.png)

2.头像栏显示为圆圈其于方框直接的地方显示为黑色
![image](https://user-images.githubusercontent.com/42086066/94369787-56db9100-00db-11eb-83c8-9a6abfe57abe.png)

**Comment by Jack-Myth** [comment]
已更新
