### ISSUE TITLE
The background of the shop is out of place with the background of the menu

### ISSUE THREAD

**Issue by BotVodka** [Jack-Myth/Threshold-Miku#38]
just have a look at the picture below:(

**Comment by BotVodka** [comment]
![Uploading QQ图片20201129202010.png…]()

**Comment by BotVodka** [comment]
![QQ图片20201129202010](https://user-images.githubusercontent.com/68559578/100541734-bd6a6000-3280-11eb-8fc2-4a2701b3bfb8.png)

**Comment by Jack-Myth** [comment]
Enable Steam URL In Steam settings,or use "New Webpage Without URL" in Customizer
