### ISSUE TITLE
表述错误？

### ISSUE THREAD

**Issue by umaron** [Jack-Myth/Threshold-Miku#41]
**主内容不透明度**那里，往左掰，主内容后面的图片越不透明？？？这应该是**主内容透明度**吧

**Comment by Jack-Myth** [comment]
主内容透明，才可以看见背景。越往右，主内容越不透明，背景越不可见。

**Comment by umaron** [comment]
但我是**越往右**，背景越**可见**。 我是Light版本的

**Comment by Jack-Myth** [comment]
思考了一下，好像换成其他词也不合适。姑且就先这么写吧:P
