### ISSUE TITLE
Steam新版本后皮肤缺失

### ISSUE THREAD

**Issue by ZeroTwo-02** [Jack-Myth/Threshold-Miku#42]
steam更新新版本后，游戏属性界面的皮肤不显示了，和早期的好友界面皮肤一样出现了问题
还请大佬注意下这个问题，顺便看看好友列表能不能在不禁用steam浏览器的前提下展开，谢谢！！
![K2LL E ENJ}$U(F7GAH~%AY](https://user-images.githubusercontent.com/61810192/103144932-a11cee80-476c-11eb-8422-449d3f7dea45.png)

**Comment by Jack-Myth** [comment]
暂时没有合理解决这些问题的方法，如果你有什么解决办法可以和我讨论讨论

**Comment by Jack-Myth** [comment]
已更新
