### ISSUE TITLE
下载和游戏中的新选项排版错了而且无法使用

### ISSUE THREAD

**Issue by EJianZQ** [Jack-Myth/Threshold-Miku#43]
![QQ图片20210102104302](https://user-images.githubusercontent.com/52780714/103449741-8526c900-4ce7-11eb-801b-7bd28eb594bf.png)
![QQ图片20210102104310](https://user-images.githubusercontent.com/52780714/103449742-8821b980-4ce7-11eb-9c0b-d18e585ad80c.png)
限制下载速度那个功能排序错了，游戏中的排序也错了，如图。请大佬修复一下

**Comment by Jack-Myth** [comment]
更新，现在应该没有了
