### ISSUE TITLE
使用里面的软件更改了MainBG，商店和好友无法打开，商店页面背景错位

### ISSUE THREAD

**Issue by DancingSnow0517** [Jack-Myth/Threshold-Miku#46]
![image](https://user-images.githubusercontent.com/60736156/106395169-9eab5580-63f8-11eb-8274-95bc850b22cf.png)

更改前商店界面
![image](https://user-images.githubusercontent.com/60736156/106395115-6572e580-63f8-11eb-9c98-c21d3743c7cb.png)
更改后商店页面无法显示和好友列表打不开

**Comment by MIUMIU-Z** [comment]
添加url地址栏

**Comment by Onism02** [comment]
同问

**Comment by weebskin** [comment]
Settings > interface > Display Web Address bar

**Comment by GhostSSR** [comment]
我也是商店打不开，但是经过我多次测试，发现图片太大的（占1-2M左右）会出现商店打不开的问题，我换上一个几百K的图片后，商店还是能正常打开

**Comment by lingfeng01** [comment]
我也是商店打不开好友也打不开
