### ISSUE TITLE
a bug about Threshold Miku Customizer 2.exe

### ISSUE THREAD

**Issue by Vash-dev** [Jack-Myth/Threshold-Miku#47]
当自定义一栏中选择为原始页面（无背景）时会修改失败并崩溃，此时页面全黑，按理来说预想的效果应该是作为普通的库代替原先自定义背景并透明化的库
（管理员权限情况下）图1.png为曾经1.5.1时的截图，图2.png为2.3.4出现bug后的图
![1](https://user-images.githubusercontent.com/21136941/109053226-72dd7000-7717-11eb-8161-68c1bb336f59.png)
![2](https://user-images.githubusercontent.com/21136941/109053445-a9b38600-7717-11eb-84c6-5d899dc3d9cf.png)

**Comment by Jack-Myth** [comment]
已确认问题，会抽时间修的。

**Comment by Jack-Myth** [comment]
再试一试，怎么样呢？
