### ISSUE TITLE
No Emotion Box....

### ISSUE THREAD

**Issue by weebskin** [Jack-Myth/Threshold-Miku#48]
![fHV3ZAPBzw](https://user-images.githubusercontent.com/56221357/115171036-5264dd00-a0ec-11eb-8193-44b5c83b85df.gif)
Help?

**Comment by Jack-Myth** [comment]
This issue seems doesn't caused by the skin, have you tried the original skin?

**Comment by weebskin** [comment]
use original skin is fine but when i use miku skin it happen.

**Comment by Jack-Myth** [comment]
takes a very very long time but it fixed now.
