### ISSUE TITLE
关于Steam的更新导致的皮肤UI问题

### ISSUE THREAD

**Issue by ZeroTwo-02** [Jack-Myth/Threshold-Miku#49]
请问大佬什么时候可以更新新的游戏属性皮肤，好友列表皮肤呢
而且在Steam设置的界面选项又出现了错位
由于向您发送邮件，您并没有回复我，所以我选择在这里留言
感谢带佬！！！

**Comment by lingfeng01** [comment]
你好，用了这个皮肤好友界面打不开

**Comment by Jack-Myth** [comment]
已更新
