### ISSUE TITLE
关于新版Steam下载页面

### ISSUE THREAD

**Issue by Na-Sizuku** [Jack-Myth/Threshold-Miku#53]
在Steam客户端bate测试中，Steam下载页面已经进行了更新，类似于大屏幕。同时老版UI的设置均不可用，还请开发者注意一下

**Comment by Jack-Myth** [comment]
“老版UI的设置均不可用”具体是什么意思？

**Comment by Na-Sizuku** [comment]
主要是Steam的下载界面完全改变了https://ibb.co/SNyDTpd
![E_ZDJJ56D$1ESK5R)W`L( R](https://user-images.githubusercontent.com/45922575/127741611-f4c44b3a-4ae8-4b3e-b49d-e23d110a226b.png)

**Comment by Jack-Myth** [comment]
已支持新下载界面，请下载最新版v2.4.0
