### ISSUE TITLE
Steam 阻止关机

### ISSUE THREAD

**Issue by ccyuyzs** [Jack-Myth/Threshold-Miku#56]
在多次重装steam测试后发现，使用此皮肤后将大大提高steam阻止系统关机的概率。不知道这个是v社背锅还是这个皮肤的问题？

**Comment by ccyuyzs** [comment]
还有一个疑惑，Threshold Miku Customizer 2.exe似乎不只是编辑器的作用？steam似乎会加载此文件以防止steam标题和返回键重叠？

**Comment by Jack-Myth** [comment]
皮肤没有相关的功能，定制器也不会被Steam加载。如果对定制器的功能存在疑惑，可以直接看[定制器的源代码](https://github.com/Jack-Myth/Threshold-Miku-Customizer-2)

**Comment by ccyuyzs** [comment]
> 皮肤没有相关的功能，定制器也不会被Steam加载。如果对定制器的功能存在疑惑，可以直接看[定制器的源代码](https://github.com/Jack-Myth/Threshold-Miku-Customizer-2)

但如果从Threshold-Miku文件夹中删除Threshold Miku Customizer 2.exe文件，则Steam标题与返回键重叠
