### ISSUE TITLE
关于Steam测试版游戏库UI不会正常使用背景

### ISSUE THREAD

**Issue by Na-Sizuku** [Jack-Myth/Threshold-Miku#59]
2022年2月1日下午17时，左右出现了Steam库UI不会正常使用背景，但是社区或者商店都会正常使用，
![image](https://user-images.githubusercontent.com/45922575/151957835-4dd9ff05-12d1-48e4-8122-f4d208f19ef2.png)这个是Steam库的背景，变成了原版背景，不会调用Steam皮肤的设定。
![image](https://user-images.githubusercontent.com/45922575/151958021-4ec7ef57-4000-43e8-bb2a-6ea250d722b9.png)这个是商店页面的，可以调用Steam皮肤的设定
**我个人认为目前是Steam库UI在度重写，所以出现了该情况，还望更新一下**

**Comment by Jack-Myth** [comment]
已知这个问题，目前在我的电脑上无法复现，等我这里出现这个问题就更新。
你可以先退出Steam测试，回到正式版来解决这个问题。

**Comment by Na-Sizuku** [comment]
好的，我这边也会继续跟进关于Steam测试版的一些相关问题，如果我有了什么发现我会第一时间给予回复的

**Comment by Jack-Myth** [comment]
已修正，看看最新版吧

**Comment by Na-Sizuku** [comment]
已经确定可以工作了，谢谢
