### ISSUE TITLE
steam主内容不透明度与主内容底色问题

### ISSUE THREAD

**Issue by YCZ01111** [Jack-Myth/Threshold-Miku#60]
主内容不透明度与主内容底色调节后重启steam没有任何变化，主内容的模糊效果调节正常，大佬能否告知这两项是调节哪里的，原谅我没有看出来

**Comment by Jack-Myth** [comment]
Steam的Beta更新导致了这个选项出了点问题。最新版本已经修复了。可以再试一下

**Comment by Jack-Myth** [comment]
稍等一下，发现了一点新问题，新版本可能要延后一会儿了

**Comment by YCZ01111** [comment]
好的，谢谢大佬

**Comment by Jack-Myth** [comment]
现在应该好了，可以试试2.4.5这个版本

**Comment by YCZ01111** [comment]
好的好的，一会我试试
