### ISSUE TITLE
steamUI如何更改颜色

### ISSUE THREAD

**Issue by YCZ01111** [Jack-Myth/Threshold-Miku#61]
steam菜单和右下角的弹窗等如何改回之前的黑底白字

**Comment by YCZ01111** [comment]
> steam菜单和右下角的弹窗等如何改回之前的黑底白字

**Comment by YCZ01111** [comment]
已找到更改方法，但设置里左边的标题栏背景无法改变，求大佬告知，我换成了白字，但设置里标题栏背景还是白色，右边正常是黑色背景

**Comment by YCZ01111** [comment]
以及主内容字体颜色没有找到更改方法

**Comment by Jack-Myth** [comment]
换用深色版，就可以了。
