### ISSUE TITLE
steam更新后库的皮肤被遮挡

### ISSUE THREAD

**Issue by EaKal1** [Jack-Myth/Threshold-Miku#62]
steam更新后库的皮肤被遮挡

**Comment by Gensokyo1995** [comment]
更新最新版本正常使用

**Comment by dyak472007** [comment]
同问，暗版有这个问题，亮版没用，已经更新最新版还是这样

**Comment by Jack-Myth** [comment]
更新最新版皮肤

**Comment by YusakakiNai** [comment]
同 出现了这个问题  更新到最新版使用默认的图片没有问题 一旦更换了图片就会出现黑色盖住了背景图片

**Comment by Jack-Myth** [comment]
> 同 出现了这个问题 更新到最新版使用默认的图片没有问题 一旦更换了图片就会出现黑色盖住了背景图片
不要直接覆盖，把皮肤全部删掉，然后把最新版本放进去
