### ISSUE TITLE
新版本主页面透明度不能开满

### ISSUE THREAD

**Issue by IkurokataI** [Jack-Myth/Threshold-Miku#65]
更新以后可以正常显示主页面了，但是设置主页面透明度拉满还是会显示一层薄薄的主内容底色，这个是我的问题还是目前版本只能这样？

**Comment by Jack-Myth** [comment]
用最新版。如果你用了最新版，那你可能开了模糊。高斯模糊在强度比较高的情况下可能会显出一点白色。
