### ISSUE TITLE
Customizer crashed

### ISSUE THREAD

**Issue by Mainak009** [Jack-Myth/Threshold-Miku#66]
customizer application crashed automatically when applying old JSON settings and click 'apply', after an update...First I thought it was a version compatibility issue, then I tested and it also crashes even when saving and loading from the current version setting.

attached are both the old and new settings below for testing.

[TMC2.zip](https://github.com/Jack-Myth/Threshold-Miku/files/8238370/TMC2.zip)

**Comment by Jack-Myth** [comment]
sorry for the delay. It was caused by a stupid bug and now it has been fixed. Try the bugfix release and see if you can apply settings normally.

**Comment by Mainak009** [comment]
yeah, I tested and the latest release does not have the issue anymore.😋
