### ISSUE TITLE
Threshold Miku Customizer 2无法打开

### ISSUE THREAD

**Issue by sheldonl3** [Jack-Myth/Threshold-Miku#69]
报错如图
![image](https://user-images.githubusercontent.com/44045052/172100847-aa0bef94-484a-4f12-9d17-45a5a888893f.png)

**Comment by Jack-Myth** [comment]
可能是.Net环境出了问题.用Powershell 运行一下
`Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP' -Recurse | Get-ItemProperty -Name version -EA 0 | Where { $_.PSChildName -Match '^(?!S)\p{L}'} | Select PSChildName, version`
看看.Net版本
