### ISSUE TITLE
Change backgrounds on Linux

### ISSUE THREAD

**Issue by ample-samples** [Jack-Myth/Threshold-Miku#70]
I am not sure if I'm being stupid but I cannot find a way to change the backgrounds on Linux. I tried it manually but looking in the source files I see no background images to replace. Is there any way to do this manually?

**Comment by Jack-Myth** [comment]
Most backgrounds can be modified by simply replace the TGA files in "graphics/JackMyth/", but there have some special backgrounds like MainBG and AppPropertiesBackground, You need to modify webkit.css, search "BeginBackground" and "BeginAppPropertiesBackground", then replace the Base64 string.

**Comment by ample-samples** [comment]
Ah very helpful, thank you. I'll see what I can do on my end!

**Comment by ample-samples** [comment]
Hi again, I'm having touble with the base64 conversion, can I ask how you converted your .tga to use in the webkit.css file? I have a 1080p .tga image to convert and it has evaluated to about 11,000,000 characters using the base64 -w 0 command. My editor is struggling to use this and I see that your base64 string is only 73,000 characters so this strikes me as very odd.

**Comment by Jack-Myth** [comment]
Because the Base64 string not from TGA. It's just jpg.
