### ISSUE TITLE
折叠边栏状态下，鼠标指向边栏时，比如“库”，弹出的子菜单放在右侧会不会更好？

### ISSUE THREAD

**Issue by AliSwitch** [Jack-Myth/Threshold-Miku#71]
弹出在下面的话，如果鼠标放的位置不合适，想要切换到下方的图标，比如从库想切换到社区，操作会不方便，需要拿开鼠标再回去。

**Comment by Jack-Myth** [comment]
https://github.com/Jack-Myth/Threshold-Miku/issues/26
