### ISSUE TITLE
关于新版Steam登录界面适配问题（Beta Steam版）

### ISSUE THREAD

**Issue by Na-Sizuku** [Jack-Myth/Threshold-Miku#72]
### 关于新版Steam登录界面适配问题（Beta Steam版）
新版Steam（Beta版）将会引入二维码登录功能**导致原有登录界面将不会无法正常应用原有皮肤内容**，同时手机版Steam也将应用此功能，目前Steam手机版Beta测试内已经应用QR扫描功能。
![$~QJU51F8`0)6X$)MSJ ~HS](https://user-images.githubusercontent.com/45922575/186588874-0c816d37-5551-4745-b083-5bbb58b34807.png)
### 关于目前Beta版Steam客户端登录界面代码情况
目前源代码进行了简单拆分已经确定是使用了部分HTML，以及部分JS。可能功能实现起来有一定难度

**Comment by Jack-Myth** [comment]
已支持，请下载2.6.0版本
