### ISSUE TITLE
关于Steam新版好友UI的设定和查阅到的一些资料

### ISSUE THREAD

**Issue by Na-Sizuku** [Jack-Myth/Threshold-Miku#75]
# **之前在查看关于Steam新版好友UI时在GitHub上发现了一个[项目](https://github.com/RoseTheFlower/newsteamchat)**
![image](https://user-images.githubusercontent.com/45922575/188613736-a577629d-da94-48d0-bc92-f85e14cd7bce.png)
项目展示成品图

## 实现逻辑
该项目通过对原有的css样式进行替换以实现新版Steam好友UI的替换，由于该操作和最早之前实现Steam新版的库UI操作是同属一个方向，因此会出现替换css样式后对其他皮肤的支持将会出现严重的bug问题

## 源码分析
由于源代码里面的 _libraryroot.custom.css_ 会直接替换掉原有Steam安装文件里的steamui/css/library.css 导致皮肤会出现背景显示不完全等各种问题。

_friends.custom.css_ 是直接替换掉原有的Steam安装文件里的clientui/css/friends.custom.css此操作使得新版Steam好友UI在离线情况下显示 _friends.custom.css_ 里的东西，而登陆后的情况将会调用 _libraryroot.custom.css_ 里的东西以实现上方的项目成品图。

## 个人见解
由于修改方式并没有对HTML和JS进行修改，实现起来主要方向是对CSS的定义。考虑到有代码的耦合和重复定义问题，目前来讲是不推荐直接将源码调用以实现完全的皮肤自定义，考虑到实现难度过于复杂，目前我没有办法提出相应的改进方案

**Comment by Jack-Myth** [comment]
这个方案因为需要直接修改Steam本身的文件，会产生各种各样的问题，应用起来也很麻烦，已经不打算用这种方式来做了。后续看Steam是否会开放好友界面的皮肤接口吧。

**Comment by Na-Sizuku** [comment]
好的，最近我的Steam Deck也入手了，我会慢慢研究Steam Deck相关的内容后续我会提供反馈的
