### ISSUE TITLE
Steam登录界面部分不显示

### ISSUE THREAD

**Issue by zaprtqa** [Jack-Myth/Threshold-Miku#77]
![Uploading QQ图片20221122122203.png…]()

**Comment by zaprtqa** [comment]
![QQ图片20221122122203](https://user-images.githubusercontent.com/105141119/203220896-08ec0110-412e-4f01-b160-51829c726a9f.png)

**Comment by zaprtqa** [comment]
![QQ图片20221122122501](https://user-images.githubusercontent.com/105141119/203221230-729108eb-5483-4295-928c-d3b11ed0977c.png)

**Comment by Jack-Myth** [comment]
试试新版本？
