### ISSUE TITLE
为什么我装载了以后只有边框变了 中间依然没有图片或渐变色之类的

### ISSUE THREAD

**Issue by 1079735997** [Jack-Myth/Threshold-Miku#8]
求大佬回答 弄这个弄了一天了 关键我还不懂编程 想搞还搞不了。。

**Comment by Jack-Myth** [comment]
VGUI皮肤只能处理边框。如果需要连带修改库界面的话需要For SteamUI的皮肤

**Comment by 1079735997** [comment]
那我需要去那里下载这个For SteamUI吗还是已经没办法了

**Comment by Jack-Myth** [comment]
https://github.com/Jack-Myth/Threshold-Miku/releases/tag/v1.2
