### ISSUE TITLE
今天开机变成了这样，库的导航那些都不见了

### ISSUE THREAD

**Issue by EaKal1** [Jack-Myth/Threshold-Miku#82]
![58}7)@{9O6QRF4{QME4KUTI](https://user-images.githubusercontent.com/100985008/211131109-ebd5d0ae-2a24-46ee-adcb-85004565be49.png)

**Comment by Jack-Myth** [comment]
这个问题正在准备修了，可以先取消Beta版

**Comment by LSDGQ** [comment]
> 这个问题正在准备修了，可以先取消Beta版

谢谢大佬 拜托尽快 皮肤用习惯了 突然原版不习惯了

**Comment by BlakeLN** [comment]
似乎是这两天的steambeta测试更新导致的

**Comment by BlakeLN** [comment]
> > 这个问题正在准备修了，可以先取消Beta版
> 
> 谢谢大佬 拜托尽快 皮肤用习惯了 突然原版不习惯了

取消steam beta更新就能正常使用皮肤了。

**Comment by Jack-Myth** [comment]
可以更新到最新版的皮肤了

**Comment by AdorableSKZ** [comment]
作者你好，我今天更新了非beta版本的steam后也出现了这种情况，请问怎么解决呢？

**Comment by AdorableSKZ** [comment]
> 非beta版本的steam，使用beta版本的皮肤包后问题已经解决了，谢谢

**Comment by Nepchico** [comment]
现在Steam正式版通道已经实装新版大屏幕了，这个问题在正式版通道也出现了
dalao可以把预发行的release改成正式发行了

**Comment by ralex126598** [comment]
今天更新的正式版steam 出现了这个情况 在等待dalao的更新0v0

**Comment by YCZ01111** [comment]
这次更新对于频繁换号玩家很不友好，不管是菜单中的“重新启动steam”“更换账户”，还是steam++中的一键切号，都默认以steam.exe来启动steam，不仅需要重新更新steam，而且还会导致库背景丢失，希望大佬可以有更好的解决办法

**Comment by MisakaOvOMikoto** [comment]
> 这次更新对于频繁换号玩家很不友好，不管是菜单中的“重新启动steam”“更换账户”，还是steam++中的一键切号，都默认以steam.exe来启动steam，不仅需要重新更新steam，而且还会导致库背景丢失，希望大佬可以有更好的解决办法

是的，我常用的steam++也出现了同样的问题。不知道作者大大是如何使用再注入的，不过steam++有一个添加steam启动参数的功能希望能派上用场，这样起码使用steam++更换账号不会破坏皮肤了。而且目前开机自启动steam也会出现同样的问题，如果能通过steam++自启动以修复皮肤问题那就太好了
![image](https://user-images.githubusercontent.com/95963109/216390049-dd5bd562-d9ed-4df9-b4cd-3ade23660d9d.png)
