### ISSUE TITLE
问一下为什么不支持PNG图片？

### ISSUE THREAD

**Issue by FinaFina233** [Jack-Myth/Threshold-Miku#84]
之前都用的PNG，后来改后缀用的PNG，现在后缀都不给改了，JPG没法用透明图层啊。。

**Comment by FinaFina233** [comment]
![7(R7%)%4I$E 02`55UB 9C](https://user-images.githubusercontent.com/52440333/213618016-f32c7676-4474-4a3e-8cdb-62e157f390b6.png)
我主要使用在这个Overlay上面，打开界面的情况下能看到游戏

**Comment by Jack-Myth** [comment]
可以把Steam更新到Beta版，然后用2.7以上的皮肤。或者从2.7的皮肤里把TMC2复制出来，替换2.6里的版本。

**Comment by FinaFina233** [comment]
> 可以把Steam更新到Beta版，然后用2.7以上的皮肤。或者从2.7的皮肤里把TMC2复制出来，替换2.6里的版本。

感谢解答
