### ISSUE TITLE
突然變這樣

### ISSUE THREAD

**Issue by LuSien2147** [Jack-Myth/Threshold-Miku#85]
![image](https://user-images.githubusercontent.com/121304920/216322410-cb4bd565-b47a-45d1-8b28-f6075022413b.png)
今天一開機就變這樣了 求救

**Comment by Jack-Myth** [comment]
https://github.com/Jack-Myth/Threshold-Miku/issues/82

**Comment by gcm626** [comment]
> #82
只能用新下载的启动器开启，会不会有封号的风险啊，有点怕被封号了。

**Comment by jonm58** [comment]
> > #82
> > 只能用新下载的启动器开启，会不会有封号的风险啊，有点怕被封号了。

不会封号

**Comment by qq2928642231** [comment]
我也是变成这样，beta测试和正式版都是这样，咋办啊

**Comment by Na-Sizuku** [comment]
最近在研究Steam库这个问题的时候发现了这个项目https://github.com/NitroxydeX/Threshold-Skin-fixes ，该项目作者通过补充一些东西以适配新版Steam库问题，不知道是否对作者有帮助
