### ISSUE TITLE
steam库界面无背景

### ISSUE THREAD

**Issue by EntropyTea** [Jack-Myth/Threshold-Miku#88]
![屏幕截图 2023-02-04 002404](https://user-images.githubusercontent.com/88919732/216654773-26ad9a24-70fe-46d2-9098-770d3daba6a0.png)
如图所示，库界面背景显示异常
steam API：v020
steam组件版本：1675222618
皮肤版本为2.4.1（其中resource文件夹被替换为2.7.1版本）
由于丢失了自定义背景的原始文件，因此希望知晓皮肤中自定义背景的存储位置或代码

**Comment by Jack-Myth** [comment]
背景位于graphics\JackMyth，皮肤不透明可以使用SteamLauncher.exe打开Steam

**Comment by RaffeYang** [comment]
> 背景位于graphics\JackMyth，皮肤不透明可以使用SteamLauncher.exe打开Steam

按照作者方法已解决
