### ISSUE TITLE
有关Steam Launcher

### ISSUE THREAD

**Issue by 0w0-Yui** [Jack-Myth/Threshold-Miku#89]
这个开源吗？我启动steam的时候有加参数的需求

**Comment by Gensokyo1995** [comment]
桌面会有一个额外生成的steam快捷方式，路径指向SteamLauncher.exe，在那里添加参数就可以了
如果没有在设置Threshold Miku Customizer 2的时候勾选创建快捷方式
![image](https://user-images.githubusercontent.com/43993884/216795589-86e8bea8-bb71-4c20-8e4c-31553bab015d.png)

**Comment by 0w0-Yui** [comment]
thx, 我晚点回去试试
