### ISSUE TITLE
How to use Collapsed Sidebar?

### ISSUE THREAD

**Issue by OriginalReimu** [Jack-Myth/Threshold-Miku#9]
I have no idea about using the files in "Customization" folder.   :-) 
<a href="https://sm.ms/image/pgWojm8NMDfnuyI" target="_blank"><img src="https://i.loli.net/2020/01/23/pgWojm8NMDfnuyI.png" ></a>

**Comment by Jack-Myth** [comment]
That's pretty easy. You can see some folder named "resource", "steamui" in “Collapsed Sidebar”, Copy them to the root folder of the skin, replace the existing files. then run "install.cmd". That is the usage of Collapsed Sidebar.
