### ISSUE TITLE
Previews里的friends

### ISSUE THREAD

**Issue by RS96C** [Jack-Myth/Threshold-Miku#91]
所以说 Previews的friends是有图片的 但是用了之后发现并没有 so why？

**Comment by Jack-Myth** [comment]
这是很久很久之前的好友界面了，现在已经没有了。

**Comment by RS96C** [comment]
行吧 还有问题 为什么自己选了图片全部替换掉原来的图片之后 点应用却没有弹出用SteamLauncher打开的提示呢 是因为图片占用太大了吗

**Comment by Jack-Myth** [comment]
检查一下有没有创建快捷方式的选项。然后没有提示是什么意思？是直接闪退了吗？

**Comment by RS96C** [comment]
是直接闪退 但是已经没事了 知道原因了 弄了张没有画布的图片

**Comment by RS96C** [comment]
下的是最新版 是直接闪退了 是图片mb大小问题？

**Comment by RS96C** [comment]
自动安装说语法错误

**Comment by Jack-Myth** [comment]
可以把错误日志发给我

**Comment by RS96C** [comment]
没有建议分辨率的那两个应该怎么弄才是最好的

**Comment by RS96C** [comment]
我发现弄了MainBG 1920x1080分辨率就不行

**Comment by RS96C** [comment]
还有overlaybg

**Comment by RS96C** [comment]
![image](https://user-images.githubusercontent.com/87936721/219614815-18a4604e-bccc-4d09-9896-2e67af932d19.png)
破案了 所以这里说的太大是占用还是分辨率

**Comment by RS96C** [comment]
没事了 我又懂了 按照平时steam的窗口设置分辨率就好
